### ISSUE TITLE
Error in HB and disconnecting

### ISSUE THREAD

**Issue by richiinfoset** [lawrencebensaid/homebridge-innova#2]
Hi

node:3479) UnhandledPromiseRejectionWarning: RequestError: Error: read ECONNRESET
   at new RequestError (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/errors.js:14:15)
   at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/plumbing.js:87:29)
   at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/plumbing.js:46:31)
   at self.callback (/usr/local/lib/node_modules/homebridge-innova/node_modules/request/request.js:185:22)
   at Request.emit (events.js:400:28)
   at Request.onRequestError (/usr/local/lib/node_modules/homebridge-innova/node_modules/request/request.js:877:8)
   at ClientRequest.emit (events.js:400:28)
   at Socket.socketErrorListener (_http_client.js:475:9)
   at Socket.emit (events.js:400:28)
   at emitErrorNT (internal/streams/destroy.js:106:8)
(node:3479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 19)

The plugin works fine until this message. Sometimes I have to click twice on HomeKit innova button and sometimes is unvaillable.
I would like to use it because it is genius for automations with blinds. If I can help you with something please tell me. :)

Thank you very much
Richard

**Comment by lawrencebensaid** [comment]
This is a very general error, could you please send me the config.json and any more info you have?
Thanks!

**Comment by richiinfoset** [comment]
Here is config for the plugin
{
    "host": "172.17.2.7",
    "name": "Innova",
    "fan": true,
    "accessory": "InnovaAirCo"
}

If you need config of HB, tell me.

**Comment by richiinfoset** [comment]
Here is all message from HB what is regarding the bug

(node:29384) UnhandledPromiseRejectionWarning: RequestError: Error: connect EHOSTUNREACH 172.17.2.7:80
    at new RequestError (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-innova/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-innova/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:29384) UnhandledPromiseRejectionWarning: RequestError: Error: connect EHOSTUNREACH 172.17.2.7:80
    at new RequestError (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-innova/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-innova/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:29384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:29384) UnhandledPromiseRejectionWarning: RequestError: Error: connect EHOSTUNREACH 172.17.2.7:80
    at new RequestError (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-innova/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-innova/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-innova/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:29384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by richiinfoset** [comment]
Hi.
I have reconfigured wifi and now it is working corectly.
Thanks
Richard
